[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
	let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'

[[plugins]]
repo = '/root/Documents/vimscript/plugins/HelloVim'

[[plugins]]
repo = '/root/Documents/vimscript/plugins/vim-ReView'

[[plugins]]
repo = '/root/Documents/vimscript/plugins/plgMaker'

